mixtape = "test:latest"

[resources]
cpus   = 2
memory = "8GiB"

[[agents]]
type = "native"
harness = "opencode"
prompt = "Use cowsay to print Hello world!"
extra_packages = [ "cowsay" ]
replicas = 10
